spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarymanagement
    username: root
    password: Chandini@5d2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
